version: "3.9"

services:
  movies:
    image: kubkusum/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: kubkusum/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: kubkusum/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
